# -*- mode: python -*-

"""
    This file is part of CBF.

    CBF is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    CBF is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CBF.  If not, see <http://www.gnu.org/licenses/>.


    Copyright 2009, 2010 Florian Paul Schmidt
"""

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	if bld.env['CBF_HAVE_KDL'] == 1 and bld.env['CBF_HAVE_EIGEN2'] == 1:
		task1 = bld.new_task_gen(
			features='cxx cprogram', 
			source='cbf_test_kdl_transforms.cc', 
			target='cbf_test_kdl_transforms', 
			includes='. ../libcbf/', 
			uselib_local='cbf')

		bld.new_task_gen(
			features='cxx cprogram', 
			source='cbf_simple_test.cc', 
			target='cbf_simple_test', 
			includes='. ../libcbf/', 
			uselib_local='cbf')

		bld.new_task_gen(
			features='cxx cprogram', 
			source='cbf_test_axis_potential.cc', 
			target='cbf_test_axis_potential', 
			includes='. ../libcbf/', 
			uselib_local='cbf')

		bld.new_task_gen(
			features='cxx cprogram', 
			source='cbf_test_axis_potential2.cc', 
			target='cbf_test_axis_potential2', 
			includes='. ../libcbf/', 
			uselib_local='cbf')

		if bld.env['CBF_HAVE_KDLCHAINVIZ'] == 1:
			task2 = bld.new_task_gen(
				features='cxx cprogram qt4', 
				source='cbf_test_kdl_transforms_view.cc', 
				target='cbf_test_kdl_transforms_view', 
				includes='. ../libcbf/', 
				uselib = 'KDLCHAINVIZ QKDLCHAINVIZ QTCORE QTGUI QTOPENGL OROCOS-KDL',
				uselib_local='cbf')
	
			if bld.env['HAVE_SPACEMOUSE'] == 1:
				task2.uselib += ' SPACEMOUSE'
	
		

		task3b = bld.new_task_gen(
			features='cxx cprogram', 
			source='cbf_test_simple_plugin_api.cc', 
			target='cbf_test_simple_plugin_api', 
			includes=['.', '../libcbf/', '../schemas'], 
			uselib_local='cbf',
			uselib = 'XERCESC')

