# -*- mode: python -*-

"""
    This file is part of CBF.

    CBF is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    CBF is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CBF.  If not, see <http://www.gnu.org/licenses/>.


    Copyright 2009, 2010 Florian Paul Schmidt
"""

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	
	if bld.env['CBF_HAVE_XSD'] == 1 and bld.env['CBF_HAVE_EIGEN2'] == 1:
		task3a = bld.new_task_gen(
			features='cc cprogram', 
			source='cbf_test_c_bindings.c', 
			target='cbf_test_c_bindings', 
			includes=['.', '../../../libcbf/', '../schemas'], 
			uselib_local='cbf',
			uselib = 'XERCESC')
		
	

